# permissions for end users to edit books.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: book-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uid-preconditions
    app.kubernetes.io/part-of: uid-preconditions
    app.kubernetes.io/managed-by: kustomize
  name: book-editor-role
rules:
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - books
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - books/status
  verbs:
  - get
