---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - books
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - books/finalizers
  verbs:
  - update
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - books/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - chapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - chapters/finalizers
  verbs:
  - update
- apiGroups:
  - author.tutorial.kubebuilder.io
  resources:
  - chapters/status
  verbs:
  - get
  - patch
  - update
