apiVersion: author.tutorial.kubebuilder.io/v1
kind: Book
metadata:
  labels:
    app.kubernetes.io/name: book
    app.kubernetes.io/instance: book-sample
    app.kubernetes.io/part-of: uid-preconditions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: uid-preconditions
  name: book-sample
  namespace: uid-preconditions-system
spec:
  # TODO(user): Add fields here
